[package]
org = "ballerina"
name = "tool_scan"
version = "@toml.version@"
distribution = "@toml.distribution@"
authors = ["Ballerina"]
keywords = ["scan", "static code analysis"]
license = ["Apache-2.0"]
repository = "https://github.com/ballerina-platform/static-code-analysis-tool"
